version: '2.1'

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      APP_DB_HOST: 'jdbc:mysql://db'
      APP_DB_NAME: 'filestorage'
      APP_DB_USERNAME: 'user'
      APP_DB_PASSWORD: 'pass'
      APP_DB_DDL: 'create'

  db:
    image: healthcheck/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: filestorage
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
